from flask import Flask, request, jsonify # Flask is a lightweight web framework for Python that allows us to create web servers and APIs easily.
from flask_cors import CORS # CORS (Cross-Origin Resource Sharing) is a security feature implemented by browsers that restricts web pages from making requests to a different domain than the one that served the web page. The flask_cors library provides an easy way to enable CORS in our Flask application, allowing our
from groq import Groq # Groq is a library that provides an interface to interact with the Groq API, which allows us to use advanced language models and tools in our application.
import os # The os module provides a way to interact with the operating system, allowing us to access environment variables, file paths, and other OS-level functionality. In this code, we use it to retrieve the GROQ_API_KEY from the environment variables for authentication with the Groq API.    
import json # The json module provides functions for working with JSON data, allowing us to parse JSON strings into Python objects and convert Python objects into JSON strings. In this code, we use it to parse the arguments of tool calls generated by the language model, which are expected to be in JSON format.
import base64 # The base64 module provides functions for encoding and decoding data in Base64 format, which is a way to represent binary data (like images or PDFs) as ASCII text. In this code, we use it to decode the Base64-encoded data of uploaded files (images or PDFs) so that we can process their content and provide it as context to the language model.
import io # The io module provides tools for working with streams of data, such as files or in-memory buffers. In this code, we use it to create an in-memory byte stream from the decoded PDF data, allowing us to read and extract text from the PDF using the PdfReader without needing to save the file to disk.
from pypdf import PdfReader # The pypdf library is a Python library for reading and manipulating PDF files. In this code, we use the PdfReader class from the pypdf library to read the content of uploaded PDF files, extract text from their pages, and provide that text as context to the language model for answering user queries related to the document.

app = Flask(__name__)
CORS(app) # Enables Cross-Origin Resource Sharing so your frontend can communicate with it
#it uses llama3.3 70b and meta-llama/llama-4-scout-17b-16e-instruct for vision tasks   
client = Groq(api_key=os.environ.get("GROQ_API_KEY"))

MODEL        = "llama-3.3-70b-versatile"
VISION_MODEL = "meta-llama/llama-4-scout-17b-16e-instruct"

# ==========================================
# 1. PYTHON TOOL FUNCTIONS
# ==========================================
def get_game_latest_news(game_name):
    game_clean = game_name.lower()
    if "gta" in game_clean or "grand theft auto 6" in game_clean:
        return "Actualité : Rockstar Games a confirmé une mise à jour majeure du moteur physique pour fin 2026."
    elif "elden ring" in game_clean:
        return "Actualité : Des rumeurs circulent sur un second DLC, mais FromSoftware se concentre sur une nouvelle IP en 2026."
    return f"Recherche web effectuée pour '{game_name}' : Le jeu est activement suivi par la communauté, aucune anomalie majeure signalée récemment."

def calculate_pc_bottleneck(cpu, gpu):
    if "i3" in cpu.lower() and "rtx 4090" in gpu.lower():
        return "Résultat du calcul : Bottleneck SEVÈRE (environ 45%). Le processeur limite grandement la carte graphique."
    return "Résultat du calcul : Configuration équilibrée (Bottleneck inférieur à 8%). Les composants fonctionnent de manière optimale."

DEVELOPED_TOOLS = {
    "get_game_latest_news": get_game_latest_news,
    "calculate_pc_bottleneck": calculate_pc_bottleneck,
}

# ==========================================
# 2. GROQ TOOL SPEC DECLARATIONS
# ==========================================
GROQ_TOOLS_SPEC = [
    {
        "type": "function",
        "function": {
            "name": "get_game_latest_news",
            "description": "Use when the user asks for recent news, release dates, or updates about a specific video game.",
            "parameters": {
                "type": "object",
                "properties": {
                    "game_name": {"type": "string", "description": "The name of the video game (e.g. GTA 6, Elden Ring)"}
                },
                "required": ["game_name"]
            }
        }
    },
    {
        "type": "function",
        "function": {
            "name": "calculate_pc_bottleneck",
            "description": "Use to evaluate whether a CPU and GPU combination will cause a performance bottleneck.",
            "parameters": {
                "type": "object",
                "properties": {
                    "cpu": {"type": "string", "description": "The CPU model (e.g. Intel Core i3-12100F)"},
                    "gpu": {"type": "string", "description": "The GPU model (e.g. NVIDIA RTX 4090)"}
                },
                "required": ["cpu", "gpu"]
            }
        }
    }
]

SYSTEM_PROMPT = """You are GameMind, an elite autonomous AI agent specialized in video games.
You have access to tools you can call to get real-time info or compute metrics.

When interpreting a query, use your tools if needed.
Once you receive the tool output, synthesize your final response.
Always format your final output using these exact sections:
- 🎯 **Plan**: Brief explanation of your multi-step approach.
- ⚙️ **Analysis**: How you processed the data or tools.
- 🎮 **Answer**: Your expert gaming response.
- 💡 **Pro Tips**: A gaming bonus insight.

CRITICAL: Detect the language used by the user. You must reply entirely in that same language.
Translate your section headers dynamically based on the language:
- In English: 🎯 **Plan**, ⚙️ **Analysis**, 🎮 **Answer**, 💡 **Pro Tips**
- In French: 🎯 **Plan**, ⚙️ **Analyse**, 🎮 **Réponse**, 💡 **Astuces Pro**
- In Arabic: 🎯 **الخطة**, ⚙️ **التحليل**, 🎮 **الإجابة**, 💡 **نصائح احترافية**
(Adapt similarly for any other language detected)."""

#route handling the chat interactions. It receives user messages and optional 
# file uploads, processes them, interacts with the Groq API to generate responses,
#  and returns the final answer to the frontend.
@app.route("/api/chat", methods=["POST"])
def chat():
    data      = request.get_json() #extracts the json body sent from the frontend
    messages  = data.get("messages", []) #grabs the hisotry of messages in the conversation, which includes user queries and model responses, to provide context for generating the next response.
    file_info = data.get("file", None) #checks if there's an uploaded file 
    if not messages:
        return jsonify({"error": "No messages provided"}), 400

    model_to_use     = MODEL #image procession and model switching 
    pdf_text_content = ""

    if file_info and messages:
        media_type  = file_info.get("media_type", "")
        base64_data = file_info.get("data", "")

        if media_type.startswith("image/"):
            last = messages[-1]
            if last["role"] == "user":
                messages[-1] = {
                    "role": "user",
                    "content": [
                        {"type": "image_url", "image_url": {"url": f"data:{media_type};base64,{base64_data}"}},
                        {"type": "text", "text": last["content"]}
                    ]
                }
                model_to_use = VISION_MODEL

        #PDF In-Memory Processing & Hard Truncation Guard        
        elif "pdf" in media_type:
            try:
                pdf_bytes   = base64.b64decode(base64_data)
                pdf_stream  = io.BytesIO(pdf_bytes)
                reader      = PdfReader(pdf_stream)
                total_pages = len(reader.pages)
                MAX_PDF_CHARS   = 20000 # Set a hard limit on PDF text to avoid overwhelming the model and hitting token limits. Adjust as needed based on typical document sizes and model capacity.
                extracted_pages = []
                total_chars     = 0
                pages_included  = 0

                for i, page in enumerate(reader.pages):
                    text = page.extract_text()
                    if not text:
                        continue
                    remaining = MAX_PDF_CHARS - total_chars
                    if remaining <= 0:
                        break
                    if len(text) > remaining:
                        text = text[:remaining] + "\n[... page truncated ...]"
                    extracted_pages.append(f"--- DOCUMENT PAGE {i+1} ---\n{text}")
                    total_chars    += len(text)
                    pages_included += 1

                pdf_text_content = "\n\n".join(extracted_pages)
                truncation_note  = ""
                if pages_included < total_pages:
                    truncation_note = (
                        f"\n[⚠️ Document truncated: {pages_included}/{total_pages} pages "
                        f"shown to stay within token limits.]\n"
                    )

                if pdf_text_content and messages[-1]["role"] == "user":
                    user_original_query = messages[-1]["content"]
                    messages[-1]["content"] = (
                        f"[ATTACHED DOCUMENT CONTEXT]{truncation_note}\n"
                        f"{pdf_text_content}\n"
                        f"=========================================\n"
                        f"USER QUESTION ABOUT THIS DOCUMENT: {user_original_query}"
                    )
            except Exception as pdf_err:
                return jsonify({"error": f"Failed to parse PDF: {str(pdf_err)}"}), 500
    # We construct the message history for the model, ensuring the system prompt is always at the beginning 
    # and removing any previous system messages to avoid confusion. 
    # This way, the model receives a clear and consistent instruction 
    # set along with the relevant conversation history and any attached document context.  
    clean_history = [m for m in messages if m["role"] != "system"]
    full_messages  = [{"role": "system", "content": SYSTEM_PROMPT}] + clean_history

    def call_without_tools(): #fallback mechanism in case the model fails to generate valid tool calls or if there's an error during tool execution.
        """Fallback: answer without tools when tool generation fails."""
        fallback = client.chat.completions.create(
            model=model_to_use,
            messages=full_messages,
            max_tokens=1500,
            temperature=0.5,
        )
        return fallback.choices[0].message.content or "No response generated."

    try:
        completion = client.chat.completions.create(
            model=model_to_use,
            messages=full_messages,
            tools=GROQ_TOOLS_SPEC,
            tool_choice="auto", #donne au model full autonomy pour décider quand utiliser les outils disponibles en fonction de la requête de l'utilisateur et du contexte de la conversation. Avec "auto", le modèle peut générer des appels d'outils de manière dynamique lorsque cela est pertinent pour répondre à la question posée, sans que nous
            max_tokens=1500,
            temperature=0.5,
        )

        response_message = completion.choices[0].message
        finish_reason    = completion.choices[0].finish_reason
        tool_calls       = response_message.tool_calls

        # Model signalled tool use but produced no valid call → fall back : it keeps the application from crashing 
        if finish_reason == "tool_calls" and not tool_calls:
            response_text = call_without_tools()

        elif tool_calls: #If tool_calls contains data, the agent enters its multi-turn orchestration cycle
            try:
                full_messages.append(response_message) # 1. Save Groq's tool intent
                for tool_call in tool_calls:
                    function_name    = tool_call.function.name
                    function_args    = json.loads(tool_call.function.arguments) # 2. break down arguments
                    function_to_call = DEVELOPED_TOOLS.get(function_name)
                    # 3. Dynamic execution with safety string fallback
                    tool_output = (
                        function_to_call(**function_args)
                        if function_to_call
                        else f"Error: unknown tool '{function_name}'"
                    )
                    #dynamic unpacking: breaks down the arguments from the tool call and passes them to the corresponding Python function. This allows for flexible and dynamic execution of tools based on the model's generated intent.
                    full_messages.append({
                        "role":         "tool",
                        "tool_call_id": tool_call.id,
                        "name":         function_name,
                        "content":      tool_output, # 4. Save your Python function output
                    })
# 5. Final Synthesis (Turn 2): The model receives the full context, including the original query, its tool call intent, and the actual output from the executed tool. It then synthesizes this information to generate a comprehensive final response that addresses the user's query effectively.
                second_completion = client.chat.completions.create(
                    model=model_to_use,
                    messages=full_messages,
                    max_tokens=1500,
                    temperature=0.5,
                )
                response_text = second_completion.choices[0].message.content

            except (json.JSONDecodeError, Exception):
                # Malformed tool arguments → retry without tools
                response_text = call_without_tools()

        else:
            response_text = response_message.content or "No response generated."

        return jsonify({"response": response_text})

    except Exception as e:
        err_str = str(e)
        # Groq 400: model generated malformed tool call JSON → retry without tools
        if "tool_use_failed" in err_str or "failed_generation" in err_str:
            try:
                return jsonify({"response": call_without_tools()})
            except Exception as fallback_e:
                return jsonify({"error": str(fallback_e)}), 500
        return jsonify({"error": err_str}), 500

#main to run the code and start the Flask server on port 5000 with debug mode enabled, allowing for easier development and troubleshooting. When you run this script, it will listen for incoming requests to the defined routes (like /api/chat) and handle them according to the logic we've implemented.
if __name__ == "__main__":
    app.run(debug=True, port=5000)